name: Deploy to VM

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to VM
      uses: appleboy/ssh-action@master
      with:
        host: 20.2.219.112
        username: azureuser
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          git pull origin master
          cd /home/azureuser/simple-backend-api
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 app.py