name: Deploy Flask API to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Deploy to virtual machine
      uses: appleboy/ssh-action@master
      with:
        host: 20.2.219.112
        username: azureuser
        key: ${{ secrets.SSH_PVT_KEY }}
        port: 80
        script: |
          # Clone the Flask API repository
          git clone https://github.com/piyushagarwal1411/simple-backend-api.git
    
          # Install the required dependencies
          cd simple-backend-api
          python -m pip install -r requirements.txt
    
          # Run the Flask app
          python app.py
          
